version: "3"

networks:
  default:
    name: "web"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - redis
    volumes:
      - ./traefik.yml:/traefik.yml:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.domain.tld`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"

  traefik-kobling:
    image: alpine-variant
    container_name: traefik-kobling
    depends_on:
      - redis
    volumes:
      - ./config.yml:/config.yml
    environment:
      REDIS_URL: "redis:6379"
      RUN_EVERY: 20

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
